# Generated by Django 4.1.13 on 2024-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_service_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icons',
            field=models.TextField(null=True),
        ),
    ]
